"""empty message

Revision ID: 77e41667090c
Revises: f1c9280be8e3
Create Date: 2022-07-24 16:27:51.599871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77e41667090c'
down_revision = 'f1c9280be8e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('admin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'categories', 'admins', ['admin_id'], ['id'])
    op.add_column('products', sa.Column('admin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'admins', ['admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'admin_id')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'admin_id')
    # ### end Alembic commands ###
